### ISSUE TITLE
Week 1- Getting Started

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#1]
We will meet every Thursday at 9:30 in FTR 230, with the course run through this Repo (and your own). 

For Thursday I would like everyone to create a repo for the course - 
@yaaminiv and laura - please create a repo that would correspond to your proteomics paper, (we will split them into two papers) specifically a repo that would published along side it. 
By Thursday, minimally have a page that documents the analysis of your SRM data, such that **I could take your data from the machine and get it out of Skyline.** 

Sam - please create a Repo on Github, and review material @ https://github.com/sr320/course-fish546-2017/wiki 
And install everything on your computer through R (going down the page)
Sam - please respond here with your github ID so I can add you as a collab.

Please respond below with any questions.

**Comment by yaaminiv** [comment]
@sr320 would you like the SRM analysis document to be housed in the proteomics paper repo, or our analysis repo? Do you want it to also include analyses in R or just from the machine through Skyline?

**Comment by sr320** [comment]
At this point is does not matter the repo - we will discuss the eventual content of the repo Thursday. 
See some of Jay’s for examples. 

In terms of content I want to be able to take raw data from the machine and visualize technical and biological replicate data.

**Comment by yaaminiv** [comment]
Where would you like us to post the link to the document when finished?

**Comment by sr320** [comment]
Here in this issue.

**Comment by yaaminiv** [comment]
[Gigas SRM Analysis Document](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb)
[paper repo](https://github.com/RobertsLab/paper-gigas-DNR-proteomics)

**Comment by SMay1** [comment]
Hi everybody, this is my first post on github!

**Comment by sr320** [comment]
@SMay1 nice! You should have received an invite to join this repo as a collaborator.

**Comment by SMay1** [comment]
@sr320 I currently do not have a Linux virtual machine on my personal laptop, but do on my desktop- for purposes of the class should I install a VM on my laptop or just use windows? If everyone else is using Linux maybe it's best that I install a VM.

**Comment by sr320** [comment]
Nobody uses linux. Laura and Yaamini (and me) use Macs.
I would not install a VM but use whatever OS you are more comfortable with
and use on a regular basis, Windows is fine.

**Comment by laurahspencer** [comment]
Repo for paper: [Paper-DNR-Geoduck-Proteomics](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics)
Series of 4 notebooks detailing steps from .raw to data analysis: [SRM notebooks](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/tree/master/notebooks/SRM)

**Comment by SMay1** [comment]
My Repo for the class: https://github.com/SMay1/FISH546
