### ISSUE TITLE
[L] Data Story

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#11]
- [ ] What is the primary story your data is telling?
- [ ] What is holding you back? providing obstacles?
- [ ] Develop a timeline where abouts you would have a completed draft of your paper by Dec 1.

**Comment by laurahspencer** [comment]
**Story:**
Juvenile geoduck placed in four sites spanning Washington State for one month produced varying levels of three proteins in their gill tissue that are involved in denatured protein refolding. Higher levels of the three proteins, HSP70, HSP90 & PDI, correlated with significantly lower pH and supersaturated DO in Fidalgo Bay & Hood Canal, as compared to Case Inlet and Willapa Bay. 

**Holding me back:**
Need environmental data from Micah
Lack of experience with several tasks = slow going 
This past week, capacity

**Potential Timeline:**

|              | Analysis                                                                             | Writing                                      |
|--------------|--------------------------------------------------------------------------------------|----------------------------------------------|
| Nov 1-5      | Re-do DIA analysis in R with notebook documentation                                  | More lit research & draft introduction       |
| Nov 6-12     | Additional SRM data analysis (follow-up to ANOSIM), dilution curve analysis notebook | SRM results DIA results                      |
| Nov 13-19    | DIA error rate, ROC curve, linear response plot                                      | Edits to introduction, and start Discussion  |
| Nov 20-26    | Refine protein box plots                                                             | More discussion                              |
| Nov 27-Dec 1 | Environmental data analysis & plots                                                  | Clean-up/edits                               |

**Comment by laurahspencer** [comment]
Here are scatter plots for the 3 proteins. Plots show transition abundances in each sample (1 point = 1 transition), color coded by site. 

![HSP90](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/analyses/SRM/scatterbysample-HSP90.png?raw=true)

![HSP70](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/analyses/SRM/scatterbysample-HSP70.png?raw=true)

![PDI](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/blob/master/analyses/SRM/scatterbysample-PDI.png?raw=true)

**Comment by laurahspencer** [comment]
@sr320 regarding the log transformation question from class yesterday: NMDS & ANOSIM are non-parametric analyses so does not require the assumption of a normal distribution.
