### ISSUE TITLE
[Y] Data reps

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#12]
- [ ] What is the primary story your data is telling?
- [ ] What are the different options for visualizing the data, list as many as possible.
- [ ] Develop a timeline where abouts you would have a completed draft of your paper by Dec 1.

**Comment by yaaminiv** [comment]
**Primary story**:
- Oysters responding to differing environmental conditions at each site by altering protein expression. Potentially driven by alternative splicing.

**Data visualization**:
- Boxplots or bar charts displaying protein expression between sites
- Boxplots or bar charts displaying expression for all proteins at a site
- ROC curves to indicate biomarker viability
- GIS map to show how my sites encompass a broad swath of environmental conditions
- NMDS if there's any sort of clustering pattern
- A map? or something to show how protein expression changes/hotspots for certain protein expression at sites/correlate with environmental conditions
- From Emma: Linear response of peptides (Peak area on the y, amount of peptide (moles) on the x)
- Some way to visualize/analyze alternative splicing? A flowchart maybe?

**Timeline**:
- Found in my [November goals](https://yaaminiv.github.io/November-Goals/) post
