### ISSUE TITLE
[Y] SRM Protocol and DIA Protocol

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#5]
@yaaminiv for this week

- [x] Address issues in SRM Protocol, listed [here](https://github.com/RobertsLab/project-oyster-oa/issues?q=is%3Aissue+is%3Aopen+label%3ASRM-protocol)
- [x] Get as far as you can going through Laura's SRM Protocol [here](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/tree/master/notebooks/SRM)
- [ ] Start DIA Protocol

**Comment by yaaminiv** [comment]
What do you mean by start DIA protocol? Are you talking about the methods in my paper? If so, those are already drafted.

**Comment by sr320** [comment]
Reproducible protocol (like what was done with SRM)

**Comment by sr320** [comment]
But be sure to tackle the first two tasks first (SRM)

**Comment by yaaminiv** [comment]
For Task 2: I'm using Skyline on Swan, but it seems like TeamViewer is inaccessible when the computer is asleep 👎 I'm going to troubleshoot this tomorrow when I'm back in the lab. I can work through the first of Laura's five notebooks before class, then will tackle the rest tomorrow.

**Comment by yaaminiv** [comment]
[Revised SRM protocol](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb)
[Feedback on Laura's protocol](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/issues/14).
[Bare bones of DIA protocol. Unusable right now/work in progress](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-10-11-DIA-Skyline-Data-Pipeline.ipynb)
