### ISSUE TITLE
[L] SRM and DIA

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2017#6]
@laurahspencer for this week 

- [ ] address issues with [SRM protocol](https://github.com/RobertsLab/Paper-DNR-Geoduck-Proteomics/issues?q=is%3Aissue+is%3Aopen+label%3ASRM-protocol)
- [ ] run [Yaamini's SRM protocol](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb) to see where issues arise (post issues to that repo).
- [ ] Write methods section

**Comment by laurahspencer** [comment]
Thanks- the issue name says "DIA" but instead it looks like I'll be writing the methods section, correct?

**Comment by sr320** [comment]
Sure but if you get those all done, the next thing creating a DIA protocol like what you did for SRM (that could be reproduced.

**Comment by laurahspencer** [comment]
Got it, thanks!

**Comment by laurahspencer** [comment]
* [Some draft language for methods](https://docs.google.com/a/uw.edu/document/d/1LEzRkAWbgG62Ju3qxKnpDVLUAPlknxGWsARVRzEzvMg/edit?usp=sharing) 
* [My feedback on Y's SRM protocol to date](https://github.com/RobertsLab/project-oyster-oa/issues/19)
